"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RevlogEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ReviewKind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ReviewKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RevlogEntry._ReviewKind.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LEARNING: RevlogEntry._ReviewKind.ValueType  # 0
        REVIEW: RevlogEntry._ReviewKind.ValueType  # 1
        RELEARNING: RevlogEntry._ReviewKind.ValueType  # 2
        FILTERED: RevlogEntry._ReviewKind.ValueType  # 3
        MANUAL: RevlogEntry._ReviewKind.ValueType  # 4

    class ReviewKind(_ReviewKind, metaclass=_ReviewKindEnumTypeWrapper): ...
    LEARNING: RevlogEntry.ReviewKind.ValueType  # 0
    REVIEW: RevlogEntry.ReviewKind.ValueType  # 1
    RELEARNING: RevlogEntry.ReviewKind.ValueType  # 2
    FILTERED: RevlogEntry.ReviewKind.ValueType  # 3
    MANUAL: RevlogEntry.ReviewKind.ValueType  # 4

    ID_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    USN_FIELD_NUMBER: builtins.int
    BUTTON_CHOSEN_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    LAST_INTERVAL_FIELD_NUMBER: builtins.int
    EASE_FACTOR_FIELD_NUMBER: builtins.int
    TAKEN_MILLIS_FIELD_NUMBER: builtins.int
    REVIEW_KIND_FIELD_NUMBER: builtins.int
    id: builtins.int
    cid: builtins.int
    usn: builtins.int
    button_chosen: builtins.int
    interval: builtins.int
    last_interval: builtins.int
    ease_factor: builtins.int
    taken_millis: builtins.int
    review_kind: global___RevlogEntry.ReviewKind.ValueType
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        cid: builtins.int = ...,
        usn: builtins.int = ...,
        button_chosen: builtins.int = ...,
        interval: builtins.int = ...,
        last_interval: builtins.int = ...,
        ease_factor: builtins.int = ...,
        taken_millis: builtins.int = ...,
        review_kind: global___RevlogEntry.ReviewKind.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["button_chosen", b"button_chosen", "cid", b"cid", "ease_factor", b"ease_factor", "id", b"id", "interval", b"interval", "last_interval", b"last_interval", "review_kind", b"review_kind", "taken_millis", b"taken_millis", "usn", b"usn"]) -> None: ...

global___RevlogEntry = RevlogEntry

@typing_extensions.final
class RevlogEntries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    NEXT_DAY_AT_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RevlogEntry]: ...
    next_day_at: builtins.int
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___RevlogEntry] | None = ...,
        next_day_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries", "next_day_at", b"next_day_at"]) -> None: ...

global___RevlogEntries = RevlogEntries
